---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.7
    attributes:
      consul_agent:
        dnsmasq:
          upstream_servers:
            - 8.8.8.8
  - name: centos-7.2
    attributes:
      consul_agent:
        dnsmasq:
          network_manager_enabled: true

suites:
  - name: default
    run_list:
      - recipe[test::default]
